/**
 * App version resolution contract (#421): the navbar version must come from the
 * operator's configuration instead of the hardcoded `v0.1` literal, and every
 * unset tier must degrade to that same visible default rather than an empty badge.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const { getProjectRoot } = vi.hoisted(() => ({ getProjectRoot: vi.fn() }));
vi.mock('$lib/server/pythonRunner', () => ({
	getProjectRoot: () => getProjectRoot(),
	runPythonScript: vi.fn()
}));

// The loader shares this module with the version contract but not its subject:
// settings resolution shells out to the real config realm, which the scratch
// project root has no script for. Stub it so the test measures the version
// passthrough only.
vi.mock('$lib/server/settings', () => ({
	loadMergedSettings: () => ({ pocketbase_url: 'http://127.0.0.1:8090' })
}));

const { resolveAppVersion, DEFAULT_APP_VERSION } = await import('$lib/server/version');
const { load } = await import('../routes/+layout.server');

let tmpRoot = '';

beforeEach(() => {
	delete process.env.APP_VERSION;
	delete process.env.PUBLIC_APP_VERSION;
	tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'app-version-'));
	getProjectRoot.mockReturnValue(tmpRoot);
});

afterEach(() => {
	delete process.env.APP_VERSION;
	delete process.env.PUBLIC_APP_VERSION;
	fs.rmSync(tmpRoot, { recursive: true, force: true });
	vi.clearAllMocks();
});

describe('resolveAppVersion precedence', () => {
	it('falls back to the preset default when nothing is configured', () => {
		expect(resolveAppVersion()).toBe(DEFAULT_APP_VERSION);
		expect(DEFAULT_APP_VERSION).toBe('v0.1');
	});

	it('prefers APP_VERSION over every other tier', () => {
		process.env.APP_VERSION = ' v9.9.9 ';
		process.env.PUBLIC_APP_VERSION = 'v2.2.2';
		fs.writeFileSync(path.join(tmpRoot, 'version.json'), '{"version":"v0.98.1"}', 'utf-8');

		expect(resolveAppVersion()).toBe('v9.9.9');
	});

	it('uses PUBLIC_APP_VERSION when APP_VERSION is unset', () => {
		process.env.PUBLIC_APP_VERSION = ' v1.2.3 ';
		fs.writeFileSync(path.join(tmpRoot, 'version.json'), '{"version":"v0.98.1"}', 'utf-8');

		expect(resolveAppVersion()).toBe('v1.2.3');
	});

	it('treats a blank env var as unset and keeps reading lower tiers', () => {
		process.env.APP_VERSION = '   ';
		process.env.PUBLIC_APP_VERSION = '';
		fs.writeFileSync(path.join(tmpRoot, 'version.json'), '{"version":"v0.98.1"}', 'utf-8');

		expect(resolveAppVersion()).toBe('v0.98.1');
	});

	it('reads the static version.json manifest generated by CI (#423)', () => {
		fs.writeFileSync(
			path.join(tmpRoot, 'version.json'),
			JSON.stringify({ version: 'v0.98.1', commit: 'abc1234', built_at: '2026-10-08' }),
			'utf-8'
		);

		expect(resolveAppVersion()).toBe('v0.98.1');
	});

	it('ignores a malformed or version-less manifest instead of failing the page', () => {
		fs.writeFileSync(path.join(tmpRoot, 'version.json'), 'not json at all', 'utf-8');
		expect(resolveAppVersion()).toBe(DEFAULT_APP_VERSION);

		fs.writeFileSync(path.join(tmpRoot, 'version.json'), '{"commit":"abc1234"}', 'utf-8');
		expect(resolveAppVersion()).toBe(DEFAULT_APP_VERSION);

		fs.writeFileSync(path.join(tmpRoot, 'version.json'), '{"version":"   "}', 'utf-8');
		expect(resolveAppVersion()).toBe(DEFAULT_APP_VERSION);
	});

	it('falls back to the default when the manifest is absent', () => {
		expect(fs.existsSync(path.join(tmpRoot, 'version.json'))).toBe(false);
		expect(resolveAppVersion()).toBe(DEFAULT_APP_VERSION);
	});
});

describe('layout loader', () => {
	/** The generated loader type is generic over the event param; assert the shape. */
	async function loadData(): Promise<{ pocketbaseUrl: string; appVersion: string }> {
		return (await (load as (event: unknown) => Promise<unknown>)({})) as {
			pocketbaseUrl: string;
			appVersion: string;
		};
	}

	it('exposes appVersion alongside pocketbaseUrl', async () => {
		delete process.env.APP_VERSION;
		delete process.env.PUBLIC_APP_VERSION;
		const data = await loadData();
		expect(data.appVersion).toBe(DEFAULT_APP_VERSION);
	});

	it('exposes the configured version to the navbar', async () => {
		process.env.APP_VERSION = 'v3.4.5';
		const data = await loadData();
		expect(data.appVersion).toBe('v3.4.5');
	});
});